version: "3.1"

services:

  config-server:
    image: hr-config-service:1.0
    container_name: config-server
    networks:
      - ms_course

  eureka-server:
    image: hr-eureka-server:1.0
    container_name: eureka-server
    networks:
      - ms_course
    restart: on-failure
    environment:
      CONFIG_SERVER_URL: 'http://config-server:8888'
    depends_on:
      - config-server
    links:
      - config-server

  oauth-server:
    image: hr-oauth:1.0
    container_name: oauth_server
    networks:
      - ms_course
    environment:
      CONFIG_SERVER_URL: 'http://config-server:8888'
      EUREKA_URL: 'http://eureka-server:8761/eureka/'
    depends_on:
      - config-server
      - eureka-server
    links:
      - config-server
      - eureka-server
    restart: on-failure

  gateway:
    image: hr-gateway:1.0
    container_name: gateway
    networks:
      - ms_course
    ports:
      - "8080:8080"
    environment:
      CONFIG_SERVER_URL: 'http://config-server:8888'
      EUREKA_URL: 'http://eureka-server:8761/eureka/'
    depends_on:
      - config-server
      - eureka-server
    links:
      - config-server
      - eureka-server
    restart: on-failure

  user:
    image: hr-user:1.0
    container_name: user
    networks:
      - ms_course
    environment:
      CONFIG_SERVER_URL: 'http://config-server:8888'
      EUREKA_URL: 'http://eureka-server:8761/eureka/'
    depends_on:
      - config-server
      - eureka-server
    links:
      - config-server
      - eureka-server
    restart: on-failure

  worker:
    image: hr-worker:1.0
    container_name: worker
    networks:
      - ms_course
    environment:
      CONFIG_SERVER_URL: 'http://config-server:8888'
      EUREKA_URL: 'http://eureka-server:8761/eureka/'
    depends_on:
      - config-server
      - eureka-server
    links:
      - config-server
      - eureka-server
    restart: on-failure

  payroll:
    image: hr-payroll:1.0
    container_name: payroll
    networks:
      - ms_course
    environment:
      CONFIG_SERVER_URL: 'http://config-server:8888'
      EUREKA_URL: 'http://eureka-server:8761/eureka/'
    depends_on:
      - config-server
      - eureka-server
    links:
      - config-server
      - eureka-server
    restart: on-failure


networks:
  ms_course: