global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
#  external_labels:
#    monitor: 'config server'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['hr_prometheus:9090']
  - job_name: 'config-server'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'config-server:8888' ]
  - job_name: 'eureka-server'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'eureka-server:8761' ]
  - job_name: 'gateway'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'gateway:8080' ]
  - job_name: 'hr-oauth'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'gateway:8080' ]
  - job_name: 'hr-payroll'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    metrics_path: "/payroll/actuator/prometheus"
    static_configs:
      - targets: [ 'gateway:8080' ]
  - job_name: 'hr-user'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    metrics_path: "/user/actuator/prometheus"
    static_configs:
      - targets: [ 'gateway:8080' ]
  - job_name: 'hr-worker'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    metrics_path: "/worker/actuator/prometheus"
    static_configs:
      - targets: [ 'gateway:8080' ]