server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: ${GIT_HUB_CONFIG_REPO:https://github.com/pgjbz/microservices-configs.git}
          default-label: main