server:
  port: 8001

springdoc:
  api-docs:
    path: /api-documentation
  swagger-ui:
    path: /documentation

info:
  app:
    version: @project.version@
    name: @project.name@
    description: @project.description@

spring:
  application:
    name: worker
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop